### ISSUE TITLE
[问题] 示例代码推理运行性能在 RTX 4090 上很差

### ISSUE THREAD

**Issue by ninehills** [baichuan-inc/baichuan-7B#11]
使用示例代码：

```python
from transformers import AutoModelForCausalLM, AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("baichuan-inc/baichuan-7B", trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained("baichuan-inc/baichuan-7B", device_map="auto", trust_remote_code=True)
inputs = tokenizer('登鹳雀楼->王之涣\n夜雨寄北->\n', return_tensors='pt')
inputs = inputs.to('cuda:0')
pred = model.generate(**inputs, max_new_tokens=512, do_sample=True)
print(tokenizer.decode(pred.cpu()[0], skip_special_tokens=True))
```

在 model.generate() 之前增加打印信息，完整的输出需要1min左右。
显存占用23GB、GPU 使用率平均80%。

**Comment by lma-c4d** [comment]
使用model.half()试试看？

**Comment by ninehills** [comment]
> 使用model.half()试试看？

使用半精度后，推理性能没有显著提升。完成推理大约在50s左右。

**Comment by ninehills** [comment]
> <img alt="image" width="1140" src="https://user-images.githubusercontent.com/18161256/246032747-72aa7ee4-51bf-494c-9c46-e4fefd41868a.png"> 使用官方测试例子，结果输出是这样的，感觉 是不是还有什么参数需要配置呢

因为他会一直续写，这是一个基础模型。

可以用 stop token来结束（比如用换行符结束）

或者等之后sft 的model

**Comment by forcemeter** [comment]
@ninehills sft model 有发布时间表吗

**Comment by vivian940425** [comment]
> 使用示例代码：
> 
> ```python
> from transformers import AutoModelForCausalLM, AutoTokenizer
> 
> tokenizer = AutoTokenizer.from_pretrained("baichuan-inc/baichuan-7B", trust_remote_code=True)
> model = AutoModelForCausalLM.from_pretrained("baichuan-inc/baichuan-7B", device_map="auto", trust_remote_code=True)
> inputs = tokenizer('登鹳雀楼->王之涣\n夜雨寄北->\n', return_tensors='pt')
> inputs = inputs.to('cuda:0')
> pred = model.generate(**inputs, max_new_tokens=512, do_sample=True)
> print(tokenizer.decode(pred.cpu()[0], skip_special_tokens=True))
> ```
> 
> 在 model.generate() 之前增加打印信息，完整的输出需要1min左右。 显存占用23GB、GPU 使用率平均80%。

你好，想问下我同样在 4090 下跑示例代码会报内存不足，不知道该如何改进？
```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1000.00 MiB (GPU 0; 23.65 GiB total capacity; 21.50 GiB already allocated; 739.31 MiB free; 21.50 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by ninehills** [comment]
> > 使用示例代码：
> > ```python
> > from transformers import AutoModelForCausalLM, AutoTokenizer
> > 
> > tokenizer = AutoTokenizer.from_pretrained("baichuan-inc/baichuan-7B", trust_remote_code=True)
> > model = AutoModelForCausalLM.from_pretrained("baichuan-inc/baichuan-7B", device_map="auto", trust_remote_code=True)
> > inputs = tokenizer('登鹳雀楼->王之涣\n夜雨寄北->\n', return_tensors='pt')
> > inputs = inputs.to('cuda:0')
> > pred = model.generate(**inputs, max_new_tokens=512, do_sample=True)
> > print(tokenizer.decode(pred.cpu()[0], skip_special_tokens=True))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 在 model.generate() 之前增加打印信息，完整的输出需要1min左右。 显存占用23GB、GPU 使用率平均80%。
> 
> 你好，想问下我同样在 4090 下跑示例代码会报内存不足，不知道该如何改进？
> 
> ```
> torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1000.00 MiB (GPU 0; 23.65 GiB total capacity; 21.50 GiB already allocated; 739.31 MiB free; 21.50 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> ```

hiyouga/LLaMA-Efficient-Tuning 这个库的demo 推理速度很快，我看了下他的推理参数，做如下调整：

其中的model path 是我本地下载的模型地址。


```python
from transformers import AutoModelForCausalLM, AutoTokenizer, AutoConfig
import torch

model_path = "./models/baichuan-7B/c87a92725454b832f4e0865c508a3507b36619a0/"
tokenizer = AutoTokenizer.from_pretrained(model_path, padding_side="left", trust_remote_code=True)
tokenizer.pad_token_id = 0 if tokenizer.pad_token_id is None else tokenizer.pad_token_id # set as the <unk> token
if tokenizer.pad_token_id == 64000:
    tokenizer.pad_token_id = 0 # for baichuan model (need fix)

config = AutoConfig.from_pretrained(model_path, trust_remote_code=True)
print(">>> load model...")

model = AutoModelForCausalLM.from_pretrained(model_path, config=config, torch_dtype=torch.float16, trust_remote_code=True, device_map="auto", low_cpu_mem_usage=True)

print(">>> start pred...")

for i in ["写一首春天的诗歌：", '登鹳雀楼->王之涣\n夜雨寄北->']:
    inputs = tokenizer(i, return_tensors='pt')
    inputs = inputs.to('cuda:0')
    print(f"start to pred: {i}")
    pred = model.generate(**inputs, max_new_tokens=64)
    print(tokenizer.decode(pred.cpu()[0], skip_special_tokens=True))
````

这个的推理速度正常了，很快

**Comment by jiacheo** [comment]
> > > > 使用示例代码：
> > > > ```python
> > > > from transformers import AutoModelForCausalLM, AutoTokenizer
> > > > 
> > > > tokenizer = AutoTokenizer.from_pretrained("baichuan-inc/baichuan-7B", trust_remote_code=True)
> > > > model = AutoModelForCausalLM.from_pretrained("baichuan-inc/baichuan-7B", device_map="auto", trust_remote_code=True)
> > > > inputs = tokenizer('登鹳雀楼->王之涣\n夜雨寄北->\n', return_tensors='pt')
> > > > inputs = inputs.to('cuda:0')
> > > > pred = model.generate(**inputs, max_new_tokens=512, do_sample=True)
> > > > print(tokenizer.decode(pred.cpu()[0], skip_special_tokens=True))
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 在 model.generate() 之前增加打印信息，完整的输出需要1min左右。 显存占用23GB、GPU 使用率平均80%。
> > > 
> > > 
> > > 你好，想问下我同样在 4090 下跑示例代码会报内存不足，不知道该如何改进？
> > > ```
> > > torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1000.00 MiB (GPU 0; 23.65 GiB total capacity; 21.50 GiB already allocated; 739.31 MiB free; 21.50 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> > > ```
> > 
> > 
> > hiyouga/LLaMA-Efficient-Tuning 这个库的demo 推理速度很快，我看了下他的推理参数，做如下调整：
> > 其中的model path 是我本地下载的模型地址。
> > ```python
> > from transformers import AutoModelForCausalLM, AutoTokenizer, AutoConfig
> > import torch
> > 
> > model_path = "./models/baichuan-7B/c87a92725454b832f4e0865c508a3507b36619a0/"
> > tokenizer = AutoTokenizer.from_pretrained(model_path, padding_side="left", trust_remote_code=True)
> > tokenizer.pad_token_id = 0 if tokenizer.pad_token_id is None else tokenizer.pad_token_id # set as the <unk> token
> > if tokenizer.pad_token_id == 64000:
> >     tokenizer.pad_token_id = 0 # for baichuan model (need fix)
> > 
> > config = AutoConfig.from_pretrained(model_path, trust_remote_code=True)
> > print(">>> load model...")
> > 
> > model = AutoModelForCausalLM.from_pretrained(model_path, config=config, torch_dtype=torch.float16, trust_remote_code=True, device_map="auto", low_cpu_mem_usage=True)
> > 
> > print(">>> start pred...")
> > 
> > for i in ["写一首春天的诗歌：", '登鹳雀楼->王之涣\n夜雨寄北->']:
> >     inputs = tokenizer(i, return_tensors='pt')
> >     inputs = inputs.to('cuda:0')
> >     print(f"start to pred: {i}")
> >     pred = model.generate(**inputs, max_new_tokens=64)
> >     print(tokenizer.decode(pred.cpu()[0], skip_special_tokens=True))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这个的推理速度正常了，很快
> 
> 看起来限制 pad token 确实有效，推理的速度快了很多。但是还是会爆显存，我用了 model.half() 能勉强跑下来。
> 
> 谢谢大佬！

你们cuda什么版本？ 我的12.0的跑不起来，报错：
>    File "/home/jiacheo/anaconda3/envs/baichuan7b/lib/python3.10/site-packages/transformers/activations.py", line 150, in forward
    return nn.functional.silu(input)
  File "/home/jiacheo/anaconda3/envs/baichuan7b/lib/python3.10/site-packages/torch/nn/functional.py", line 2059, in silu
    return torch._C._nn.silu(input)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by ninehills** [comment]
根据 pytorch 的页面，我选的是torch=2.0.1 加cuda 11.8的组合。

https://pytorch.org/get-started/locally/

**Comment by cywjava** [comment]
参照如下修改：可以提高生成速度 。

**Comment by cywjava** [comment]
import os

from transformers import AutoTokenizer, AutoModelForCausalLM, AutoConfig
import torch

PRE_TRAINED_MODEL_PATH = "../model/"


# 程序入口
def main():
    os.environ["CUDA_VISIBLE_DEVICES"] = "2"
    tokenizer = AutoTokenizer.from_pretrained(PRE_TRAINED_MODEL_PATH, trust_remote_code=True)
    tokenizer.pad_token_id = 0 if tokenizer.pad_token_id is None else tokenizer.pad_token_id  # set as the <unk> token
    if tokenizer.pad_token_id == 64000:
        tokenizer.pad_token_id = 0  # for baichuan model (need fix)

    config = AutoConfig.from_pretrained(PRE_TRAINED_MODEL_PATH, trust_remote_code=True)
    model = AutoModelForCausalLM.from_pretrained(PRE_TRAINED_MODEL_PATH, config=config, torch_dtype=torch.float16,
                                                 trust_remote_code=True, device_map="auto", low_cpu_mem_usage=True)
    with torch.autocast("cuda"):
        while True:
            try:
                input_txt = input("user:")
                inputs = tokenizer(input_txt, return_tensors='pt')
                inputs = inputs.to("cuda:0")
                response = model.generate(**inputs, max_new_tokens=64, repetition_penalty=1.1)
                response = tokenizer.decode(response.cpu()[0], skip_special_tokens=True)
                print("bot:", response)
                torch.cuda.empty_cache()
            except Exception as e:
                print(e)
                break


if __name__ == '__main__':
    main()
