### ISSUE TITLE
感觉底座模型的对话能力不行啊 所以是针对这些特殊下游任务比较有优势 要增加对话能力还得做SFT？

### ISSUE THREAD

**Issue by runwean** [baichuan-inc/baichuan-7B#18]
输入：
inputs = tokenizer('用中文介绍一下百川大模型', return_tensors='pt')
pred = model.generate(**inputs, max_new_tokens=48, do_sample=True)
print(tokenizer.decode(pred.cpu()[0], skip_special_tokens=True))

输出：
用中文介绍一下百川大模型
中文的
百川,是百川融媒信息科技有限公司的名称,我们致力于“为广大企业提供从企业成立到发展壮大、从小到大的全寿命管理解决方案,帮助企业实现价值最大化。” 
百川融媒信息科技有限公司由中国知名新媒体教育培训品牌“麦派学堂”联合《大河报》发起成立。
百川融媒信息科技有限公司通过对新媒体运营、新技术、新产品研发等方面的创新和推广,建立服务于全国中小企业的行业生态,使百川融媒成为帮助客户提升企业价值的行业典范。

输入：
inputs = tokenizer('你是谁', return_tensors='pt')
pred = model.generate(**inputs, max_new_tokens=48, do_sample=True)
print(tokenizer.decode(pred.cpu()[0], skip_special_tokens=True))

输出：
你是谁?
你曾经对一个人好,可那个人并不知道。这世上没有不透风的墙,他一定会后悔的。
你好:
 这句话的字面上的意思是(那个人)曾经对你好,

**Comment by xiangrongzeng** [comment]
开源的是预训练基座模型，没有经过sft所以不适合做对话任务，用户可以在基座模型的基础上继续做sft

**Comment by chenchch94** [comment]
后续会提供对话任务的demo吗？ @xiangrongzeng

**Comment by runwean** [comment]
@xiangrongzeng 好的 感谢

**Comment by hanswang73** [comment]
> 开源的是预训练基座模型，没有经过sft所以不适合做对话任务，用户可以在基座模型的基础上继续做sft

后继会发布chat版本吗 @xiangrongzeng

**Comment by xiangrongzeng** [comment]
@chenchch94 @hanswang73 目前没有计划开源sft版本的，不过可以参考 #23 ，很容易就实现了lora版本的聊天模型
