### ISSUE TITLE
有demo的体验地址吗？

### ISSUE THREAD

**Issue by michaelhadoop** [baichuan-inc/baichuan-7B#2]

**Comment by dddddjcole** [comment]
这么好的模型，不给个在线体验

**Comment by AAChartModel** [comment]
确实, 工具上手难度太高, 潜在用户很容易被劝退

**Comment by forcemeter** [comment]
稍等，正在抓紧调试中，晚上就能出来了，大佬们，给我点时间

**Comment by Hzzhang-nlp** [comment]
> 稍等，正在抓紧调试中，晚上就能出来了，大佬们，给我点时间

想知道，你的显卡配置

**Comment by shibing624** [comment]
> 稍等，正在抓紧调试中，晚上就能出来了，大佬们，给我点时间

你demo里面放SFT后的模型吧？

**Comment by yidweahzaimen** [comment]
> 稍等，正在抓紧调试中，晚上就能出来了，大佬们，给我点时间

哥 就等你了
