### ISSUE TITLE
预训练数据epoch数

### ISSUE THREAD

**Issue by guozhiyao** [baichuan-inc/baichuan-7B#26]
请问下，预训练中的数据都是走一个epoch吗？还是说中文数据部分会走多于一个epoch？

**Comment by zmsn-2077** [comment]
hi, @guozhiyao,
本次开源主要是公开 pretrain 的 `7B model` 给社区使用，训练细节并不在本次开源的计划内，请持续关注本repo，如有新的开源内容会及时更新在`repo`中。
