### ISSUE TITLE
基座问题

### ISSUE THREAD

**Issue by ScottishFold007** [baichuan-inc/Baichuan-7B#4]
请问，发布的这个模型，是经过SFT（有监督指令微调）后的版本吗？还是预训练后未做其他训练的版本？

**Comment by zmsn-2077** [comment]
hi, @ScottishFold007 
这个开源的模型是预训练后未做其他训练的版本

**Comment by leisangcs** [comment]
> 

有lora 或者pt之类的预训练代码吗

**Comment by hanswang73** [comment]
> hi, @ScottishFold007 这个开源的模型是预训练后未做其他训练的版本

@zmsn-2077 后继会发布chat版本吗？

**Comment by Fan9** [comment]
评测的结果是基于sft和RLHF的版本，目前是开源了基础版本是么？

**Comment by zmsn-2077** [comment]
> 评测的结果是基于sft和RLHF的版本，目前是开源了基础版本是么？

是的

**Comment by zmsn-2077** [comment]
> > hi, @ScottishFold007 这个开源的模型是预训练后未做其他训练的版本
> 
> @zmsn-2077 后继会发布chat版本吗？

本次开源内容没有包括chat版本，后续有计划陆续公布，请持续关注！

**Comment by cklsoft** [comment]
不开放SFT版本怎么复现结果。。。

**Comment by zmsn-2077** [comment]
> 不开放SFT版本怎么复现结果。。。

请问您是指复现什么结果？
