### ISSUE TITLE
[Question] RTX 3060 12G能跑起来不？

### ISSUE THREAD

**Issue by yale8848** [baichuan-inc/baichuan-7B#41]
### Required prerequisites

- [X] I have read the documentation <https://github.com/baichuan-inc/baichuan-7B/blob/HEAD/README.md>.
- [X] I have searched the [Issue Tracker](https://github.com/baichuan-inc/baichuan-7B/issues) and [Discussions](https://github.com/baichuan-inc/baichuan-7B/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/baichuan-inc/baichuan-7B/discussions/new).

### Questions

RTX 3060 12G能跑起来不？

### Checklist

- [X] I have provided all relevant and necessary information above.
- [X] I have chosen a suitable title for this issue.

**Comment by cywjava** [comment]
你想多了哟。。

**Comment by jiacheo** [comment]
A10 24G 基本也是显存跑满，推理还挺慢的，12G的估计要量化成int8才行。

**Comment by lanny2018** [comment]
跑不起来，肯定！除非它后期出个int8或int4的版本。但你可以用cpu跑，速度也还可以的，模型载入代码修改一下：

**Comment by yale8848** [comment]
好的，谢谢了，各位兄弟
