### ISSUE TITLE
[Question] Evaluation的结果是基于刚pretrained完的，还是经过SFT+HFRL的？

### ISSUE THREAD

**Issue by racerandom** [baichuan-inc/baichuan-7B#45]
### Required prerequisites

- [X] I have read the documentation <https://github.com/baichuan-inc/baichuan-7B/blob/HEAD/README.md>.
- [X] I have searched the [Issue Tracker](https://github.com/baichuan-inc/baichuan-7B/issues) and [Discussions](https://github.com/baichuan-inc/baichuan-7B/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/baichuan-inc/baichuan-7B/discussions/new).

### Questions

抱歉，我没能找到足够的描述。
这些测评结果是基于刚pre-train完的checkpoint，还是已经做过SFT+HFRL了？

### Checklist

- [X] I have provided all relevant and necessary information above.
- [X] I have chosen a suitable title for this issue.

**Comment by maojinyang** [comment]
应该没有进行SFT和RLHF训练，目前发布的模型是单纯的语言模型

**Comment by Elfsong** [comment]
SFT是什么?

**Comment by GradientGuru** [comment]
pre-train only
