### ISSUE TITLE
[Question] 能提供一个类似页面聊天框的web_demo.py么？

### ISSUE THREAD

**Issue by UTimeStrange** [baichuan-inc/baichuan-7B#47]
### Required prerequisites

- [X] I have read the documentation <https://github.com/baichuan-inc/baichuan-7B/blob/HEAD/README.md>.
- [X] I have searched the [Issue Tracker](https://github.com/baichuan-inc/baichuan-7B/issues) and [Discussions](https://github.com/baichuan-inc/baichuan-7B/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/baichuan-inc/baichuan-7B/discussions/new).

### Questions

如题，像chatGLM那样.

### Checklist

- [X] I have provided all relevant and necessary information above.
- [X] I have chosen a suitable title for this issue.

**Comment by skiffer-git** [comment]
可以用这个IM项目，配合callback就能成为一个聊天系统。
https://github.com/OpenIMSDK
