### ISSUE TITLE
[Question] 请问为何tokenize以后没有bos_token?

### ISSUE THREAD

**Issue by yzxyzh** [baichuan-inc/baichuan-7B#48]
### Required prerequisites

- [X] I have read the documentation <https://github.com/baichuan-inc/baichuan-7B/blob/HEAD/README.md>.
- [X] I have searched the [Issue Tracker](https://github.com/baichuan-inc/baichuan-7B/issues) and [Discussions](https://github.com/baichuan-inc/baichuan-7B/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/baichuan-inc/baichuan-7B/discussions/new).

### Questions

感谢你们的工作！我有个小小的疑问，为何使用你们的tokenizer以后，没有bos_token呢？我因为代码频繁告警才发现了这点。
比如同样的一句话，What is your name?

使用llama的tokenizer以后，结果是：
1,  1724,   338,   596,  1024, 29973
可以看到1就是bos_token
而使用你们的tokenizer以后，结果是：
2276,  715,  879, 1868,   81
没有bos_token。

请问这个是刻意为之的吗？因为我看了你们的special_token_map，里面是有bos token的。那我后续使用，是需要人工加上这个bos_token，还是就这么不用管他，直接tokenize的东西进去推理即可？

### Checklist

- [X] I have provided all relevant and necessary information above.
- [X] I have chosen a suitable title for this issue.

**Comment by lanny2018** [comment]
因为这模型训练的时候就没加，你看代码  cc = self.sp.EncodeAsIds(line.strip()) + [self.EOS_TOKEN_ID]
它这行代码只加了一个EOS。
其实BOS_TOKEN确实完全可以不用加，模型是知道什么时候开始的。但如果你训练时加了，那就必须加，训练时不加那就不能加，不然它不认识。

**Comment by yzxyzh** [comment]
> 因为这模型训练的时候就没加，你看代码 cc = self.sp.EncodeAsIds(line.strip()) + [self.EOS_TOKEN_ID] 它这行代码只加了一个EOS。 其实BOS_TOKEN确实完全可以不用加，模型是知道什么时候开始的。但如果你训练时加了，那就必须加，训练时不加那就不能加，不然它不认识。

明白了，主要是和我现有的FT代码冲突了，代码一直在报警。如果是这样，那我就放心了，感谢解答。
