### ISSUE TITLE
[Question] 不看测试数据集，我就问一个问题 "你好"

### ISSUE THREAD

**Issue by zjcanjux** [baichuan-inc/baichuan-7B#58]
### Required prerequisites

- [X] I have read the documentation <https://github.com/baichuan-inc/baichuan-7B/blob/HEAD/README.md>.
- [X] I have searched the [Issue Tracker](https://github.com/baichuan-inc/baichuan-7B/issues) and [Discussions](https://github.com/baichuan-inc/baichuan-7B/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/baichuan-inc/baichuan-7B/discussions/new).

### Questions

![截屏2023-06-19 上午9 38 49](https://github.com/baichuan-inc/baichuan-7B/assets/37158421/1aaa5440-5697-444a-95c6-0dc380a68c3d)
这回答？说不过去吧？

### Checklist

- [X] I have provided all relevant and necessary information above.
- [X] I have chosen a suitable title for this issue.

**Comment by jiacheo** [comment]
这模型只是底模，不是chat模型，要变成chat需要自己finetune

**Comment by zjcanjux** [comment]
> 这模型只是底模，不是chat模型，要变成chat需要自己finetune


那为什么这也的问题也不对呢？
![截屏2023-06-19 下午8 31 06](https://github.com/baichuan-inc/baichuan-7B/assets/37158421/7bada76e-2da4-4c35-a73a-a1c4e3298aec)


> as for a base model, it's reasonable :)

![截屏2023-06-19 下午8 31 06](https://github.com/baichuan-inc/baichuan-7B/assets/37158421/1c2d810d-4ece-4891-85e0-f987addb1454)
那为什么这也的问题也不对呢？

**Comment by zmsn-2077** [comment]
> > > 这模型只是底模，不是chat模型，要变成chat需要自己finetune
> > 
> > 
> > 那为什么这也的问题也不对呢？ ![截屏2023-06-19 下午8 31 06](https://user-images.githubusercontent.com/37158421/246829917-7bada76e-2da4-4c35-a73a-a1c4e3298aec.png)
> > > as for a base model, it's reasonable :)
> > 
> > 
> > ![截屏2023-06-19 下午8 31 06](https://user-images.githubusercontent.com/37158421/246830009-1c2d810d-4ece-4891-85e0-f987addb1454.png) 那为什么这也的问题也不对呢？
> 
> LOL, this is absurd. In theory, without SFT, the base model indeed might not be as prone to giving the right answers. Of course, that also depends on the pre-training data... Anyway, enough of that. Baichuan's performance on this issue just doesn't cut the mustard. X）

这个不是取决于训练的预料嘛，这次补全恰好采样到了这类分布，我觉得倒是还好的，可以多试试几次。
