### ISSUE TITLE
[Question] 一个简单的概念性问题

### ISSUE THREAD

**Issue by TaiChiTiger** [baichuan-inc/baichuan-7B#59]
### Required prerequisites

- [X] I have read the documentation <https://github.com/baichuan-inc/baichuan-7B/blob/HEAD/README.md>.
- [X] I have searched the [Issue Tracker](https://github.com/baichuan-inc/baichuan-7B/issues) and [Discussions](https://github.com/baichuan-inc/baichuan-7B/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/baichuan-inc/baichuan-7B/discussions/new).

### Questions

请问这个模型和T5相比有哪些区别？是否也统一到了文本对文本的问题？
最后，您现在有要推出Instructed版本的时间线吗？

### Checklist

- [X] I have provided all relevant and necessary information above.
- [X] I have chosen a suitable title for this issue.

**Comment by TaiChiTiger** [comment]
readme写基于transformer架构，我以为是编码器-解码器架构，后面说与LLaMA相似，那最后还是解码器架构，这块是我看错了，抱歉

**Comment by GDUTT1** [comment]
所以请问有sft版本的时间线吗

**Comment by moseshu** [comment]
> readme写基于transformer架构，我以为是编码器-解码器架构，后面说与LLaMA相似，那最后还是解码器架构，这块是我看错了，抱歉

他们的readme写的有点模糊，明明跟Llama的结构差不多，为什么不直接用Llama 从scrach训练一版中文，真是搞不懂，后面llama直接用多语种训练一版，商业化之后，谁还用这些呢
