### ISSUE TITLE
ceval的评测结果，是基于预训练模型的吗？评测脚本报错

### ISSUE THREAD

**Issue by xiaozhu1106** [baichuan-inc/baichuan-7B#61]
### Required prerequisites

- [X] I have read the documentation <https://github.com/baichuan-inc/baichuan-7B/blob/HEAD/README.md>.
- [X] I have searched the [Issue Tracker](https://github.com/baichuan-inc/baichuan-7B/issues) and [Discussions](https://github.com/baichuan-inc/baichuan-7B/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/baichuan-inc/baichuan-7B/discussions/new).

### Questions

ceval的评测结果，是基于预训练模型的？ 还是基于指令微调之后的？ 
下载了ceval数据集后，直接基于您提供的评测脚本运行不通过：
shot=5  # few-shot
gpu=0  # 显卡id
split=test  # 评估测试集
model_id=baichuan-7b   # 待评估的模型
task=ceval  # 任务名称：ceval
echo gpu_idx-${gpu}-${model_id}_${task}_${split}_${shot}-shot
nohup python  evaluate_zh.py --gpu_idx ${gpu} --model_id ${model_id} --task ${task} --shot ${shot} --split ${split} --show_detail  > ${model_id}_${task}_${split}_${shot}-shot_record.txt 2>&1 &

报错内容如下：
ValueError: Couldn't cast
id: int64
question: string
A: string
B: string
C: string
D: string
answer: string
explanation: string
-- schema metadata --
pandas: '{"index_columns": [{"kind": "range", "name": null, "start": 0, "' +
1118
to
{'id': Value(dtype='int64', id=None), 'question': Value(dtype='string',
id=None), 'A': Value(dtype='string', id=None), 'B': Value(dtype='string',
id=None), 'C': Value(dtype='string', id=None), 'D': Value(dtype='string',
id=None)}
because column names don't match

### Checklist

- [X] I have provided all relevant and necessary information above.
- [X] I have chosen a suitable title for this issue.

**Comment by brotherb** [comment]
+1，我也报这个错

**Comment by Truoji** [comment]
我之前遇到这个错是因为数据集问题，我将CEVAL_DATA_PATH路径直接设置为从hugging face的ceval库下载下来的ceval-exam.py文件，将ceval-exam.py文件里面的_URL路径改为本地下载的zip文件。能够使用该脚本进行ceval的评测

**Comment by foreveryl** [comment]
应该是ceval 版本不一致. 之前评测chatglm离线下载过. 

解决办法: 直接从huggingface 下载 ceval 即可. 
CEVAL_DATA_PATH = 'ceval/ceval-exam'

**Comment by zmsn-2077** [comment]
> ceval的评测结果，是基于预训练模型的？ 还是基于指令微调之后的？

ceval的评测结果是基于预训练模型的。相关bug已经fix了，可以重新试一试
