### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by axia75** [baichuan-inc/baichuan-7B#63]
### Required prerequisites

- [X] I have read the documentation <https://github.com/baichuan-inc/baichuan-7B/blob/HEAD/README.md>.
- [X] I have searched the [Issue Tracker](https://github.com/baichuan-inc/baichuan-7B/issues) and [Discussions](https://github.com/baichuan-inc/baichuan-7B/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [ ] Consider asking first in a [Discussion](https://github.com/baichuan-inc/baichuan-7B/discussions/new).

### Questions

使用 llamaCpp convert float 16 量化 报错 KeyError: 'model.layers.0.self_attn.q_proj.weight'，请问可以支持使用llamaCpp进行量化吗

### Checklist

- [X] I have provided all relevant and necessary information above.
- [X] I have chosen a suitable title for this issue.

**Comment by GradientGuru** [comment]
参照Readme中的第三方work
