### ISSUE TITLE
请问会开源pretrain数据吗？

### ISSUE THREAD

**Issue by guozhiyao** [baichuan-inc/baichuan-7B#7]

**Comment by zmsn-2077** [comment]
hi, @guozhiyao,
目前还没有开源pretrain数据的计划，请持续关注repo，后续新的开源内容会及时更新在repo里面。

**Comment by guozhiyao** [comment]
> hi, @guozhiyao, 目前还没有开源pretrain数据的计划，请持续关注repo，后续新的开源内容会及时更新在repo里面。

@zmsn-2077 请问预训练中，1.2T数据里中英文数据的比例概是多少呢？

**Comment by zmsn-2077** [comment]
> > hi, @guozhiyao, 目前还没有开源pretrain数据的计划，请持续关注repo，后续新的开源内容会及时更新在repo里面。
> 
> @zmsn-2077 请问预训练中，1.2T数据里中英文数据的比例概是多少呢？

中文会多一些
