### ISSUE TITLE
[Question] 百川7B显存占用大，且训练训练低

### ISSUE THREAD

**Issue by expresschen** [baichuan-inc/baichuan-7B#75]
### Required prerequisites

- [X] I have read the documentation <https://github.com/baichuan-inc/baichuan-7B/blob/HEAD/README.md>.
- [X] I have searched the [Issue Tracker](https://github.com/baichuan-inc/baichuan-7B/issues) and [Discussions](https://github.com/baichuan-inc/baichuan-7B/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/baichuan-inc/baichuan-7B/discussions/new).

### Questions

机器A100*8
1. 其它llama的7B模型在zero2的时候可以训练单卡的batch=1时的seqlen=4096, 百川模型只能训练到seqlen=2048
2. 训练速度其它模型可以达到3300token/s/gpu,百川只有2200token/s/gpu
求解答

### Checklist

- [X] I have provided all relevant and necessary information above.
- [X] I have chosen a suitable title for this issue.

**Comment by wac81** [comment]
单卡你是用默认dp配置吗？baichuan这个单卡怎么都跑不起来，stage2 就超显存了
