### ISSUE TITLE
拉个群呗，老哥，免费测试呀！

### ISSUE THREAD

**Issue by aimen123** [baichuan-inc/Baichuan-7B#8]
拉个群呗，老哥，免费测试呀！

**Comment by lucasjinreal** [comment]
![image](https://github.com/baichuan-inc/baichuan-7B/assets/21303438/2974bde1-d616-40ba-b162-e2e5eea1b3b3)

民间群

**Comment by Alan05252023** [comment]
帮忙拉一下，进不去了、。

**Comment by Colin-J-Bee** [comment]
> ![image](https://user-images.githubusercontent.com/21303438/246010999-2974bde1-d616-40ba-b162-e2e5eea1b3b3.png)
> 
> 民间群

可以帮忙拉一下吗，wx：JiaoShouEcho

**Comment by runwean** [comment]
还有最新的吗 已经超过两百人了 
可以帮忙拉进群吗 万分感谢 wx：runwean

**Comment by corlin** [comment]
帮忙拉群， wx: corlin

**Comment by EternalKsana** [comment]
求帮忙拉群，wx：EternalKsana

**Comment by y210xtx** [comment]
求拉一下，wx：tushle

**Comment by luefei** [comment]
帮忙拉群: wx: NoClinging

**Comment by fredrickrsq** [comment]
求拉：wx: rsq950625

**Comment by MiXianif** [comment]
感谢好心的老哥，
帮忙拉进群: wx:NameALe

**Comment by edisonzf2020** [comment]
帮忙拉进群，wx:tiger_197408

**Comment by controZheng** [comment]
帮忙拉进群，wx:531587909

**Comment by xinyu1607** [comment]
帮忙拉群：heyucs

**Comment by RealForce1024** [comment]
帮忙拉群: fqc337940626

**Comment by tianyuso** [comment]
求拉：ztc_hebut

**Comment by HocherCN** [comment]
求拉：hongchenq730

**Comment by kant1999** [comment]
求拉： HENRY_ZH4NG

**Comment by chenjiaqiangmax** [comment]
vx：erdumh370

**Comment by oldbirdgo** [comment]
帮忙拉群: oldbirdsweet

**Comment by exaggerated-dream** [comment]
vx:hlxxzt

**Comment by rayqiu0509** [comment]
求拉，VX：qiurui

**Comment by drestart17** [comment]
求拉：vx：d1114815474

**Comment by nuass** [comment]
求拉 vx：diam05

**Comment by conghui** [comment]
求拉 vx：heconghui2621

**Comment by kobenaxie** [comment]
帮忙拉群，wx: kobena

**Comment by focoxor** [comment]
求拉 vx：WZ21200519
@lucasjinreal

**Comment by Xingkangze** [comment]
求拉 vx: z13233267743

**Comment by tingxinli1** [comment]
求拉，vx: LiTingXin0000

**Comment by cywjava** [comment]
求拉 wx:   cywjava

**Comment by formath** [comment]
wx: ForMath

**Comment by nkmeng** [comment]
求拉,vx：Hasanahm_

**Comment by jiahut** [comment]
wx：jiahut

**Comment by uestcsongtaoli** [comment]
v: Love_Whisperer

**Comment by wongwubin** [comment]
求拉：wangwubin009866

**Comment by Eggrolling-hu** [comment]
vx:    cyclone_center

**Comment by wanglaiqi** [comment]
vx:1191580068

**Comment by yeemojune** [comment]
求拉群啊，vx：Iner0208

**Comment by the0604** [comment]
求拉群lhl_no_worries
