### ISSUE TITLE
这个模型如何做多项选择呢？[Question] 

### ISSUE THREAD

**Issue by sc-lj** [baichuan-inc/baichuan-7B#90]
### Required prerequisites

- [X] I have read the documentation <https://github.com/baichuan-inc/baichuan-7B/blob/HEAD/README.md>.
- [X] I have searched the [Issue Tracker](https://github.com/baichuan-inc/baichuan-7B/issues) and [Discussions](https://github.com/baichuan-inc/baichuan-7B/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/baichuan-inc/baichuan-7B/discussions/new).

### Questions

想使用这个模型做多项选择，那么请问如何使用这个模型做多项选择呢？

### Checklist

- [X] I have provided all relevant and necessary information above.
- [X] I have chosen a suitable title for this issue.

**Comment by GradientGuru** [comment]
这个属于Discussion范畴了
